# .bashrc --- bash configuration 
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
# Set prompt
PS1="\u [\!]:\t:\w\n  >> \[\e[0m\]"
# default Envs
export ESHELL='/usr/bin/bash'
export ORGANIZATION='anticorp'
export TERM='xterm-256color'
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export ALTERNATE_EDITOR=''
export EDITOR='emacsclient -t'
export VISUAL='emacsclient -c'

# path
export PATH="$HOME/go/bin:$HOME/.nimble/bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/bin:$PATH"
export PATH="$HOME/bin/sh:$HOME/bin/py:$HOME/bin/hs:$HOME/bin/ps:$HOME/.roswell/bin:$PATH"

# custom configs
export FREESOUND_CONFIG="~/.config/freesound.json"

# aliases
macsman() {
    emacsclient -c -e "(man \"$1\")"
}

alias eman=macsman

alias vi='emacsclient -t'
alias vim='emacsclient -t'
alias ec='emacsclient -c'
alias et='emacsclient -t'
alias hgpu='hg pull -u'
alias hgc='hg ci -m'
alias hgp='hg push'

# VCS
alias hgsub='find . -name ".hg" -type d | grep -v "\./\.hg" | xargs -n1 dirname | xargs -iREPO hg -R REPO'

alias q='QHOME=~/q rlwrap -r ~/q/l64/q'
alias ..='cd ..'
complete -c man which
