#+TITLE: cfg
#+AUTHOR: ellis
Configuration files and other useful things.

As is customary, you should feel free to steal anything you find
useful in this repo, but the really useful things are often refactored
into libraries or programs.

If my memory serves me right, an earlier iteration of this project was
a single org file consisting of a Doom Emacs configuration. Then I
added non-Emacs configs like bash,ssh,gpg and started using Nix for
all my configuration. Eventually I abandoned Nix and resorted back to
the 'standard' melting-pot system configuration methodology.

Our current philosophy is to collect as many pieces of configuration
that are necessary to get me a 'usable' system by my standards. There
is no =cfg= the library or API, although I've experimented with
various ideas (=shed=, =babel=, =fig=) which could implement such
functionality, I haven't arrived at a perfect solution.

- [2023-06-13 Tue 22:45] \\
  Right now, my focus is on portable, deployable, system distributions
  of the Linux variety. The goal is to build custom Arch Linux images
  and all the machinery involved to deploy images to the following
  machines:
  - PinePhone Pro (arm)
  - Desktops/Laptops (on-site deploy, x86)
  - Podman container
  - QEMU (arm/x86 VM)
  - AWS EC2
